[package]
name = "fs"
version = "0.1.0"
authors = ["Tommy Pujol <git@itstommy.xyz>"]
edition = "2018"

[dependencies]
message-io = "0.14.2"
serde = "1.0.127"
bincode = "1.3.3"
sanitize-filename = "0.3.0"
uuid = { version = "0.8.2", features = ["v4"] }
